### ISSUE TITLE
Doesn't work with static LNURL paymentlinks

### ISSUE THREAD

**Issue by tscharly** [boltcard/bolt-card-pos#21]
App doesn't work with static LNURLs, which makes it nearly useless as a POS device because you don't know what customers are presenting, Boltcard or regular NTAG 21x with static link. Please integrate LNURL in this great app!

**Comment by robertclarkson** [comment]
Hi @tscharly, help me understand - this PoS app is nearly useless because it doesn't support static LNURLw links? 

Is it correct that Static LNURLws are mainly for "gift cards" ?  are static LNURLw's really that useful?

**Comment by tscharly** [comment]
With LNURLw links you can use simplest and cheapest NTAGs as a payment device. Of course it's insecure, but quick and cheap. At a bar of a bitcoin-event people present all kinds of NFC-devices to pay for their beer and mainly they have LNURLws stored at them.

**Comment by PeterRounce** [comment]
Static LNURLw links are ok as one time use gift cards only.
They need to be swept in full due to the lack of replay protection.
It's also overkill using an NFC card for a static in most cases when they could be a printed QR code.

Dynamic LNURLw links (i.e. bolt cards) are a different thing - they enable multiple use payment cards.
The additional active features of NXP NTAG 424 DNA cards are fully used to enable this.

I think we should avoid 'insecure'. I note that bolt cards are also quick and cheap.

**Comment by robertclarkson** [comment]
Static LNURLw links now supported in version https://github.com/boltcard/bolt-card-pos/releases/tag/v1.5.0

**Comment by tscharly** [comment]
Great, thanks!
